version: '3.8'

services:
  db:
    image: postgres:latest  # Используем образ PostgreSQL
    container_name: postgres_db    # Имя контейнера
    ports:
      - "5432:5432"                # Пробрасываем порт 5432
    environment:
      POSTGRES_USER: myuser        # Имя пользователя базы данных
      POSTGRES_PASSWORD: mypassword  # Пароль пользователя
      POSTGRES_DB: mydatabase      # Имя базы данных
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Хранение данных

volumes:
  postgres_data:                 # Определяем том для хранения данных
